# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rating_pb2 as rating__pb2


class RatingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.lastRating = channel.unary_unary(
                '/RatingService/lastRating',
                request_serializer=rating__pb2.LastRatingRequest.SerializeToString,
                response_deserializer=rating__pb2.LastRatingResponse.FromString,
                )


class RatingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def lastRating(self, request, context):
        """Definice endpointu
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RatingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'lastRating': grpc.unary_unary_rpc_method_handler(
                    servicer.lastRating,
                    request_deserializer=rating__pb2.LastRatingRequest.FromString,
                    response_serializer=rating__pb2.LastRatingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RatingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RatingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def lastRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RatingService/lastRating',
            rating__pb2.LastRatingRequest.SerializeToString,
            rating__pb2.LastRatingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
