version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    # environment:
      # RABBITMQ_DEFAULT_USERNAME: guest
      # RABBITMQ_DEFAULT_PASSWORD: guest

    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    image: mongo
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: mongo
      # MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_AUTH_USERNAME: mongo
      # ME_CONFIG_MONGODB_AUTH_PASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/