# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rating.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crating.proto\";\n\x11LastRatingRequest\x12\x16\n\x0e\x63offee_shop_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\",\n\rRatingMessage\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"5\n\x12LastRatingResponse\x12\x1f\n\x07ratings\x18\x01 \x03(\x0b\x32\x0e.RatingMessage2F\n\rRatingService\x12\x35\n\nlastRating\x12\x12.LastRatingRequest\x1a\x13.LastRatingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rating_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LASTRATINGREQUEST']._serialized_start=16
  _globals['_LASTRATINGREQUEST']._serialized_end=75
  _globals['_RATINGMESSAGE']._serialized_start=77
  _globals['_RATINGMESSAGE']._serialized_end=121
  _globals['_LASTRATINGRESPONSE']._serialized_start=123
  _globals['_LASTRATINGRESPONSE']._serialized_end=176
  _globals['_RATINGSERVICE']._serialized_start=178
  _globals['_RATINGSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
