version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo
#    environment:
#      - MONGO_INITDB_DATABASE=wab_4_11h
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
#      - ME_CONFIG_BASICAUTH_USERNAME=admin
#      - ME_CONFIG_BASICAUTH_PASSWORD=pass   
    ports:
      - 8081:8081

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.4
    ports:
      - 5000:5000
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d:ro
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    ports:
      - 9200:9200
      - 9300:9300
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config:/usr/share/kibana/config:ro